### ISSUE TITLE
Одинаковые примеры для разных вещей

### ISSUE THREAD

**Issue by Shugar** [rtivital/jsraccoon#44]
Привет! 
Нашел косяк: примеры для сдвига в вправо/влево и сдвига вниз одинаковые.

![image](https://cloud.githubusercontent.com/assets/5647725/22015629/f2946e5a-dcb3-11e6-989f-6b66ce22c928.png)

https://github.com/rtivital/jsraccoon/blob/master/articles/css-1-placeholders.md

**Comment by rtivital** [comment]
@Shugar возможно ты можешь нам помочь и создать pull request с исправленным примером?
